# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('bribe', models.CharField(blank=True, max_length=30)),
                ('place', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
