# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160128_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bribe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
